# An example configuration file.
---
APPROACHES:
  my-oracle:  # used in constructing the experiment ID
    NAME: "oracle"
    FLAGS: []
  nsrt-learning:
    NAME: "nsrt_learning"
    FLAGS:
      disable_harmlessness_check: True  # just an example
ENVS:
  my-cover:  # used in constructing the experiment ID
    NAME: "cover"
    FLAGS: []
  single-block-cover:
    NAME: "cover"
    FLAGS:
      cover_num_blocks: 1
      cover_block_widths: [0.1]
ARGS:
  - "debug"
FLAGS:  # general flags
  num_train_tasks: 20
  num_test_tasks: 10
BRANCH: "supercloud-yaml3"
START_SEED: 456
NUM_SEEDS: 2
